blueprint:
  name: 定时备份
  description: 凌晨4点，自动备份
  domain: automation
  source_url: https://github.com/shaonianzhentan/ha_file_explorer/blob/master/blueprints/backup.yaml
  input:
    start_backup:
      name: 开始备份
      description: 调用文件上传服务
      default:
        - service: ha_file_explorer.upload
      selector:
        action: {}
trigger:
- platform: time_pattern
  hours: '4'
  minutes: '0'
  seconds: '0'
action: !input 'start_backup'